version: "3"
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --requirepass H2I3iP39ChReHjqPxA3o
    networks:
     - ringcentral
    ports:
      - "6379:6379"
    volumes:
      - "redis.conf:/conf/redis.conf"
      - "redisData:/data/"
    command: redis-server /conf/redis.conf

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: H2I3iP39ChReHjqPxA3o
    volumes:
      - "mongoData:/data/db"
    networks:
      - ringcentral
    ports:
      - '27017:27017'
      
networks:
  ringcentral:
    external: true

